[package]
name = "rtfparser"
version = "1.1.1"
authors = []
edition = "2021"

[lib]
name = "rtfparser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.1"
derivative = "2.2.0"