[package]
name = "rtfparser"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rtfparser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
rtf-parser = "=0.1.1"
