[package]
name = "rtfparser"
version = "1.0.0"
authors = []
edition = "2021"

[lib]
name = "rtfparser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
derivative = "2.2.0"